apiVersion: v1 
kind: Pod 
metadata: 
    name: redis-pod
    labels: 
      name: redis-pod
      app: vks-voting-app
spec:
  containers:
    - name: redis-pod
      image: redis  
      ports:
        - containerPort: 6379