apiVersion: v1
kind: Pod
metadata: 
  name: result-pod
  labels: 
    name: result-pod
    app: vks-voting-app
spec: 
  containers: 
    - name: result-pod
      image: kodekloud/examplevotingapp_result:v1
      ports: 
        - containerPort: 80

