apiVersion: v1
kind: Pod
metadata: 
  name: voting-pod
  labels: 
    name: voting-pod
    app: vks-voting-app
spec: 
  containers: 
    - name: voting-pod
      image: kodekloud/examplevotingapp_vote:v1
      ports: 
        - containerPort: 80

